# Generated by Django 4.1 on 2022-08-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=20, null=True)),
                ('apellido', models.CharField(blank=True, max_length=20, null=True)),
                ('correo_electronico', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_usuario', models.CharField(blank=True, max_length=10, null=True)),
                ('id_factura', models.BigIntegerField(primary_key=True, serialize=False)),
                ('id_producto', models.IntegerField(blank=True, null=True)),
                ('id_pedido', models.IntegerField(blank=True, null=True)),
                ('precio', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'factura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('id_pedido', models.IntegerField(blank=True, null=True)),
                ('id_producto', models.IntegerField(blank=True, null=True)),
                ('nombre_producto', models.CharField(blank=True, max_length=10, null=True)),
                ('precio', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pedidos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Producto')),
                ('precio', models.IntegerField(blank=True, null=True, verbose_name='Precio')),
                ('nombre_producto', models.CharField(blank=True, max_length=10, null=True, verbose_name='Nombre Del Producto')),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('id_tipo_rol', models.CharField(blank=True, max_length=15, null=True)),
                ('id_estado', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
    ]
